version: '3.8'

services:
  # Web App (flovite)
  app:
    image: ghcr.io/flowee-ru/flovite:latest
    restart: always
    depends_on:
      - caddy
    env_file: .env

  # Flowee API
  api:
    image: ghcr.io/flowee-ru/api:latest
    restart: always
    env_file: .env
    depends_on:
      - caddy
      - mongo
    environment:
      API_PORT: 8081
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: flowee
  
  # mediamtx
  monday:
    image: ghcr.io/flowee-ru/mediamtx:main
    restart: always
    ports:
      - ${RTMP_PORT}:1935
      - 8888:8888
    depends_on:
      - caddy
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: flowee

  # MongoDB database
  mongo:
    image: mongo:6-jammy
    restart: always
    volumes:
      - ./data/db:/data/db

  # Caddy web server
  caddy:
    image: caddy
    restart: always
    env_file: .env
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config