version: '3.8'

services:
  # Flowee App
  app:
    image: ghcr.io/flowee-ru/app:main
    restart: always
    ports:
      - ${APP_PORT}:3000
    env_file: ./config/app.env

  # Flowee API
  api:
    image: ghcr.io/flowee-ru/api:main
    restart: always
    ports:
      - ${API_PORT}:8000
    env_file: ./config/api.env
  
  # Monday RTMP server
  monday:
    image: ghcr.io/flowee-ru/monday:main
    restart: always
    ports:
      - ${MONDAY_PORT}:8089
      - 1935:1935
    env_file: ./config/monday.env

  # MongoDB database
  mongo:
    image: mongo:6-jammy
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/db:/data/db

  # Caddy web server
  caddy:
    image: caddy
    restart: always
    env_file:
      - ./config/caddy.env
      - ./config/app.env # hosts
    ports:
      - ${PORT}:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config