version: '3.8'

services:
  # Web App (flovite)
  app:
    image: ghcr.io/flowee-ru/flovite:latest
    restart: always
    ports:
      - ${DC_APP_PORT}:8080
    env_file: .env
    volumes:
      - ./.env:/usr/src/app/.env

  # Flowee API
  api:
    image: ghcr.io/flowee-ru/api:latest
    restart: always
    ports:
      - ${DC_API_PORT}:8081
    env_file: .env
    environment:
      API_PORT: 8081
  
  # Monday RTMP server
  monday:
    image: ghcr.io/flowee-ru/monday:latest
    restart: always
    ports:
      - ${DC_MONDAY_PORT}:8082
      - ${DC_RTMP_PORT}:1935
    env_file: .env
    environment:
      MONDAY_PORT: 8082
      MONDAY_RTMP_PORT: 1935

  # MongoDB database
  mongo:
    image: mongo:6-jammy
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/db:/data/db

  # Caddy web server
  caddy:
    image: caddy
    restart: always
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config
    env_file: .env