version: '3.8'

services:
  # Flowee API
  api:
    image: ghcr.io/flowee-ru/api:main
    env_file:
      - api.env
  
  # Monday RTMP server
  monday:
    image: ghcr.io/flowee-ru/monday:main
    env_file:
      - monday.env