version: '3.8'

services:
  # Web App (flovite)
  app:
    image: ghcr.io/flowee-ru/flovite:main
    restart: always
    depends_on:
      - caddy
    ports:
      - ${DC_APP_PORT}:8080
    env_file: .env

  # Flowee API
  api:
    image: ghcr.io/flowee-ru/api:main
    restart: always
    env_file: .env
    ports:
      - ${DC_API_PORT}:8081
    depends_on:
      - caddy
      - mongo
    environment:
      API_PORT: 8081
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: flowee
  
  # Monday RTMP server
  monday:
    image: ghcr.io/flowee-ru/monday:main
    restart: always
    env_file: .env
    ports:
      - ${DC_MONDAY_PORT}:8082
      - ${DC_RTMP_PORT}:1935
    depends_on:
      - caddy
      - mongo
    environment:
      MONDAY_PORT: 8082
      MONDAY_RTMP_PORT: 1935
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: flowee

  # MongoDB database
  mongo:
    image: mongo:6-jammy
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db

  # Caddy web server
  caddy:
    image: caddy
    restart: always
    env_file: .env
    ports:
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy-data:/data
      - ./data/caddy-config:/config